; NSIS owns installer localization independently of the Electron application locale.
!ifdef BUILD_UNINSTALLER
LangString UNINSTALL_DATA_TITLE ${LANG_ENGLISH} "Choose local data to remove"
LangString UNINSTALL_DATA_TITLE ${LANG_SIMPCHINESE} "选择要清除的本机数据"
LangString UNINSTALL_DATA_SUBTITLE ${LANG_ENGLISH} "All data is kept by default for future installations."
LangString UNINSTALL_DATA_SUBTITLE ${LANG_SIMPCHINESE} "默认保留所有数据，便于重新安装后继续使用。"
LangString UNINSTALL_DATA_INTRO ${LANG_ENGLISH} "The application will be uninstalled. You can also remove the following data:"
LangString UNINSTALL_DATA_INTRO ${LANG_SIMPCHINESE} "应用程序将被卸载。你也可以选择清除以下数据："
LangString UNINSTALL_LOCAL ${LANG_ENGLISH} "Remove desktop application data and caches"
LangString UNINSTALL_LOCAL ${LANG_SIMPCHINESE} "清除桌面应用本地数据和缓存"
LangString UNINSTALL_LOCAL_DETAIL ${LANG_ENGLISH} "Includes browser storage and downloaded updates."
LangString UNINSTALL_LOCAL_DETAIL ${LANG_SIMPCHINESE} "包括浏览器存储和自动更新下载缓存。"
LangString UNINSTALL_ALL ${LANG_ENGLISH} "Remove all Harness data (also affects the CLI)"
LangString UNINSTALL_ALL ${LANG_SIMPCHINESE} "清除全部 Harness 数据（也会影响命令行版 CLI）"
LangString UNINSTALL_DESKTOP ${LANG_ENGLISH} "Remove desktop plugins and configuration"
LangString UNINSTALL_DESKTOP ${LANG_SIMPCHINESE} "清除桌面插件和配置"
LangString UNINSTALL_DESKTOP_DETAIL ${LANG_ENGLISH} "Selected alone, keeps sessions and shared settings."
LangString UNINSTALL_DESKTOP_DETAIL ${LANG_SIMPCHINESE} "单独选择时，保留会话及共享设置。"
LangString UNINSTALL_ALL_WARNING ${LANG_ENGLISH} "Uninstalling will permanently delete all sessions, settings, API keys, plugins and runtimes, including data shared with the CLI. This cannot be undone.$\r$\n$\r$\nFolder: $UnHome"
LangString UNINSTALL_ALL_WARNING ${LANG_SIMPCHINESE} "卸载时将永久删除所有会话、设置、API 密钥、插件及运行环境，也会影响命令行版（CLI）。此操作无法撤销。$\r$\n$\r$\n将删除的数据目录：$UnHome"
LangString UNINSTALL_DATA_FAILED ${LANG_ENGLISH} "Could not safely remove all selected data. Some files may already have been removed. Close programs using this folder and retry, or keep the data.$\r$\n$\r$\nFolder: $UnTarget"
LangString UNINSTALL_DATA_FAILED ${LANG_SIMPCHINESE} "无法安全清除所选数据，部分文件可能已经删除。请关闭占用此目录的程序后重试，或保留数据。$\r$\n$\r$\n目录：$UnTarget"
LangString UNINSTALL_HOME_CONFLICT ${LANG_ENGLISH} "This folder overlaps retained Harness data, or the data location could not be verified. Uninstallation has stopped. Move your Harness data to a separate folder and launch Desktop again before retrying.$\r$\n$\r$\nFolder: $UnTarget"
LangString UNINSTALL_HOME_CONFLICT ${LANG_SIMPCHINESE} "此目录与需要保留的 Harness 数据重叠，或无法确认数据位置，卸载已停止。请将 Harness 数据移到独立目录并重新启动 Desktop 后重试。$\r$\n$\r$\n目录：$UnTarget"
!endif
LangString INSTALLER_INSTALL ${LANG_ENGLISH} "Install now"
LangString INSTALLER_INSTALL ${LANG_SIMPCHINESE} "立即安装"
LangString INSTALLER_FINISH ${LANG_ENGLISH} "Finish"
LangString INSTALLER_FINISH ${LANG_SIMPCHINESE} "完成"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_ENGLISH} "Preparing installation… %d%%"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_SIMPCHINESE} "正在准备安装… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_ENGLISH} "Extracting files… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_SIMPCHINESE} "正在解压文件… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_ENGLISH} "Installing files… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_SIMPCHINESE} "正在安装文件… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_ENGLISH} "Finishing installation… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_SIMPCHINESE} "正在完成安装… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_ENGLISH} "Cleaning temporary files… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_SIMPCHINESE} "正在清理临时文件… %d%%"
LangString INSTALLER_CHOOSE_PATH ${LANG_ENGLISH} "Choose location"
LangString INSTALLER_CHOOSE_PATH ${LANG_SIMPCHINESE} "选择安装位置"
LangString INSTALLER_BROWSE ${LANG_ENGLISH} "Browse"
LangString INSTALLER_BROWSE ${LANG_SIMPCHINESE} "选择"
LangString INSTALLER_LAUNCH ${LANG_ENGLISH} "Launch now"
LangString INSTALLER_LAUNCH ${LANG_SIMPCHINESE} "立即启动"
LangString INSTALLER_LAUNCH_FAILED ${LANG_ENGLISH} "DeepSeek Harness could not be launched. Retry, or clear Launch now and close the installer."
LangString INSTALLER_LAUNCH_FAILED ${LANG_SIMPCHINESE} "无法启动 DeepSeek Harness。请重试，或取消勾选立即启动后关闭安装程序。"
LangString INSTALLER_UI_ERROR ${LANG_ENGLISH} "The installer could not initialize its window. Close it and try again."
LangString INSTALLER_UI_ERROR ${LANG_SIMPCHINESE} "无法初始化安装窗口，请关闭后重试。"
LangString INSTALLER_THEME_ERROR ${LANG_ENGLISH} "Use /THEME=auto, /THEME=light or /THEME=dark."
LangString INSTALLER_THEME_ERROR ${LANG_SIMPCHINESE} "主题参数须为 /THEME=auto、/THEME=light 或 /THEME=dark。"
LangString INSTALLER_FAILED ${LANG_ENGLISH} "Installation did not finish. Close this installer and retry. If the problem persists, download the installer again."
LangString INSTALLER_FAILED ${LANG_SIMPCHINESE} "安装未完成，请关闭安装程序后重试。如仍然失败，请重新下载安装包。"
LangString INSTALLER_RUNNING ${LANG_ENGLISH} "DeepSeek Harness is running. Close the application, then run this installer again."
LangString INSTALLER_RUNNING ${LANG_SIMPCHINESE} "DeepSeek Harness 正在运行。请先关闭应用，再重新运行安装程序。"
LangString INSTALLER_PATH_INVALID ${LANG_ENGLISH} "Choose a full local folder path. Drive roots, system folders, links and special characters are not supported."
LangString INSTALLER_PATH_INVALID ${LANG_SIMPCHINESE} "请选择本地磁盘上的完整文件夹路径，不能使用磁盘根目录、系统目录、链接目录或包含特殊字符的路径。"
LangString INSTALLER_PATH_OWNERSHIP ${LANG_ENGLISH} "Choose an empty folder or the registered DeepSeek Harness installation folder."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_SIMPCHINESE} "请选择空文件夹，或 DeepSeek Harness 原来的安装目录。"
LangString INSTALLER_PATH_WRITABLE ${LANG_ENGLISH} "This location is not writable. Choose a folder available to the current user."
LangString INSTALLER_PATH_WRITABLE ${LANG_SIMPCHINESE} "无法写入此位置。请选择当前用户可写入的文件夹；安装程序不会申请管理员权限。"
LangString INSTALLER_DISK_SPACE ${LANG_ENGLISH} "There is not enough free disk space. Choose another location."
LangString INSTALLER_DISK_SPACE ${LANG_SIMPCHINESE} "此磁盘的可用空间不足，请选择其他位置。"
LangString INSTALLER_PER_USER ${LANG_ENGLISH} "This installer supports the current user only. Uninstall the existing all-users installation first."
LangString INSTALLER_PER_USER ${LANG_SIMPCHINESE} "此安装程序仅支持当前用户。请先卸载已有的所有用户安装版本。"
